import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
// import "react-beautiful-timeline/dist/style.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ThemeProvider from "@/components/shared/ThemeProvider";
import { cx } from "class-variance-authority";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bharath Lakkoju",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          "antialiased bg-[#f0f7ff] dark:bg-[#111010] max-w-2xl lg:max-w-7xl mb-40 flex flex-col mx-4 mt-8 lg:mx-auto dark:bg-dot-white/[0.15] bg-dot-black/[0.2]",
          spaceGrotesk.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
